### ISSUE TITLE
use of sed in scipt

### ISSUE THREAD

**Issue by Jancs-E** [incognico/scripts#1]
Hi!

Running the script I get  list of errors:
sed: -e expression #1, char 12: unterminated `s' command
sed: -e expression #1, char 13: unterminated `s' command
sed: -e expression #1, char 13: unterminated `s' command
sed: -e expression #1, char 12: unterminated `s' command
sed: -e expression #1, char 11: unterminated `s' command
sed: -e expression #1, char 12: unterminated `s' command
sed: -e expression #1, char 8: unterminated `s' command
sed: -e expression #1, char 13: unterminated `s' command
sed: -e expression #1, char 19: unterminated `s' command
sed: -e expression #1, char 18: unterminated `s' command
sed: -e expression #1, char 19: unterminated `s' command

bash 4.3.053, sed 4.2.2, grep 2.14

Janis

**Comment by incognico** [comment]
In postfix-zabbix-stats.bash?

**Comment by Jancs-E** [comment]
Do not remember - solved somehow...
